/*
 * DSS Media Center
 * Grupo 53
 */
package media_center.Presentation;

import javax.swing.JOptionPane;
import media_center.DAOs.*;
import media_center.Business.*;

/**
 *
 * @author puyol
 */
public class ModifyUI extends javax.swing.JFrame {
    private LoggedInUI adminLogged = null;
    private UserMenuUI userLogged = null;
  
    public ModifyUI(LoggedInUI l) {
        this.adminLogged = l;
        initComponents();
        this.setLocationRelativeTo(null);
        User user = adminLogged.getUser();
        
        jTextField1.setText(user.getUsername()); 
        jTextField2.setText(user.getPassword()); 
        jTextField3.setText(user.getNome()); 
        jTextField4.setText(user.getEmail());
    }
    
    public ModifyUI(UserMenuUI u) {
        this.userLogged = u;
        initComponents();
        this.setLocationRelativeTo(null);
        User user = userLogged.getUser();
        
        jTextField1.setText(user.getUsername()); 
        jTextField2.setText(user.getPassword());
        jTextField3.setText(user.getNome());
        jTextField4.setText(user.getEmail());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Change User Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 24))); // NOI18N

        jButton2.setBackground(new java.awt.Color(153, 204, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(204, 255, 255));
        jTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder("Username"));

        jTextField2.setBackground(new java.awt.Color(204, 255, 255));
        jTextField2.setBorder(javax.swing.BorderFactory.createTitledBorder("Password"));

        jTextField3.setBackground(new java.awt.Color(204, 255, 255));
        jTextField3.setBorder(javax.swing.BorderFactory.createTitledBorder("Name"));

        jTextField4.setBackground(new java.awt.Color(204, 255, 255));
        jTextField4.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));

        jButton3.setBackground(new java.awt.Color(153, 204, 255));
        jButton3.setText("Change");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(153, 204, 255));
        jButton4.setText("Change");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(153, 204, 255));
        jButton5.setText("Change");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(153, 204, 255));
        jButton6.setText("Change");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 12)); // NOI18N
        jButton1.setText("DELETE ACCOUNT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                    .addComponent(jTextField2)
                    .addComponent(jTextField1)
                    .addComponent(jTextField4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // BACK BUTTON
        this.dispose();
        if(adminLogged!=null){
            adminLogged.setVisible(true);
        }
        if(userLogged!=null){
            userLogged.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // USERNAME CHANGE BUTTON
        User user = adminLogged!=null ? adminLogged.getUser() : userLogged.getUser();
        UserDAO udao = new UserDAO();
        String new_nick = jTextField1.getText();
        
        if(!new_nick.isEmpty() && !new_nick.equals(user.getUsername()) && !udao.containsKey(new_nick)){
            String old_nick = user.getUsername();
            user.setUsername(new_nick);
            udao.changeInfo(old_nick, user);
            System.out.println("Successfully changed username.");
            JOptionPane.showMessageDialog(this, "Successfully changed username.");
        } else{
            System.out.println("Invalid username.");
            JOptionPane.showMessageDialog(this, "Invalid username.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // PASSWORD CHANGE BUTTON
        User user = adminLogged!=null ? adminLogged.getUser() : userLogged.getUser();
        UserDAO udao = new UserDAO();
        String new_pass = jTextField2.getText();
        
        if(!new_pass.isEmpty() && !new_pass.equals(user.getPassword())){
            user.setPassword(new_pass);
            udao.changeInfo(user.getUsername(), user);
            System.out.println("Successfully changed password.");
            JOptionPane.showMessageDialog(this, "Successfully changed password.");
        } else{
            System.out.println("Please insert a valid different password.");
            JOptionPane.showMessageDialog(this, "Please insert a valid different password.");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // NAME CHANGE BUTTON
        User user = adminLogged!=null ? adminLogged.getUser() : userLogged.getUser();
        UserDAO udao = new UserDAO();
        String new_name = jTextField3.getText();
        
        if(!new_name.isEmpty() && !new_name.equals(user.getNome())){
            user.setNome(new_name);
            udao.changeInfo(user.getUsername(), user);
            System.out.println("Successfully changed name.");
            JOptionPane.showMessageDialog(this, "Successfully changed name.");
        } else{
            System.out.println("Please insert a valid different name.");
            JOptionPane.showMessageDialog(this, "Please insert a valid different name.");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // EMAIL CHANGE BUTTON
        User user = adminLogged!=null ? adminLogged.getUser() : userLogged.getUser();
        UserDAO udao = new UserDAO();
        String new_mail = jTextField4.getText();
        
        if(!new_mail.isEmpty() && !new_mail.equals(user.getEmail())){
            user.setEmail(new_mail);
            udao.changeInfo(user.getUsername(), user);
            System.out.println("Successfully changed email.");
            JOptionPane.showMessageDialog(this, "Successfully changed email.");
        } else{
            System.out.println("Please insert a valid different email.");
            JOptionPane.showMessageDialog(this, "Please insert a valid different email.");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // DELETE ACCOUNT BUTTON
        User user = adminLogged!=null ? adminLogged.getUser() : userLogged.getUser();
        UserDAO udao = new UserDAO();
        udao.remove(user.getUsername());
        System.out.println("Successfully deleted account.");
        JOptionPane.showMessageDialog(this, "Successfully deleted account.");
        this.dispose();
        
        if(adminLogged!=null){
            adminLogged.dispose();
        }
        if(userLogged!=null){
            userLogged.dispose();
        }
        
        new InitUI().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
